# Generated by Django 5.2.6 on 2025-10-07 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("correo", models.EmailField(max_length=254, unique=True)),
                ("contrasena_hash", models.CharField(max_length=255)),
                (
                    "rol",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Docente"), (2, "Estudiante")],
                        null=True,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="fotos_perfil/"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "usuario",
                "managed": False,
            },
        ),
    ]
